title:    Silvia Bebawy
logo: assets/img/logo_photo.png
description: >
  <br><br>
  Welcome to my portfolio page.
  <br><br>
  A little about me: 
  I'm a computer engineer and an ex-flight attendant in the process of transitioning my career to data science.
  <br><br>
  I am excited about the prospect of combining my passion for analytics and coding proficiency with my problem-solving and representation skills to make a meaningful impact in the field.
  <br><br>
  <a href="https://www.linkedin.com/in/silvia-bebawy-255565150/">View My LinkedIn Profile</a>
theme: jekyll-theme-minimal
github:
  is_project_page: false
  
